services:
  # Usando a versão mais recente do Zookeeper
  zookeeper:
    image: zookeeper:3.7  # Atualizando para uma versão mais recente e compatível com o Docker v2
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  # Kafka com a configuração do Zookeeper atualizado
  kafka:
    image: wurstmeister/kafka:latest  # Usando a versão mais recente do Kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Alterado para refletir o nome do serviço Kafka na rede Docker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - app-network

  # Cliente Service
  cliente-service:
    build: ./cliente-service
    container_name: cliente-service
    ports:
      - "8081:8080"
    depends_on:
      - kafka
    networks:
      - app-network

  # Pedido Service
  pedido-service:
    build: ./pedido-service
    container_name: pedido-service
    ports:
      - "8082:8080"
    depends_on:
      - kafka
    networks:
      - app-network

  # Estoque Service
  estoque-service:
    build: ./estoque-service
    container_name: estoque-service
    ports:
      - "8083:8080"
    depends_on:
      - kafka
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

